const a = [1]
a.push(2)
console.error(a)
a.push(3)
